//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public string CompanyName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string PostCode { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Bank1Name { get; set; }
        public string Bank1AccountName { get; set; }
        public string Bank1SortCode { get; set; }
        public string Bank1AccountNo { get; set; }
        public string Bank1IBAN { get; set; }
        public string BANK1Swift { get; set; }
        public Nullable<int> MaxInvoiceCreditAge { get; set; }
    }
}
