//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Credit()
        {
            this.PalletMovement1 = new HashSet<PalletMovement>();
        }
    
        public int CreditID { get; set; }
        public int CustomerID { get; set; }
        public string CreditReasonID { get; set; }
        public Nullable<int> PalletMovementID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string CreditorPayment { get; set; }
        public string PaymentMethodID { get; set; }
        public string PaymentRef { get; set; }
        public bool WholeInvoiceAmount { get; set; }
        public decimal Amount { get; set; }
        public decimal VAT { get; set; }
        public string Notes { get; set; }
        public bool Cancel { get; set; }
        public System.DateTime Date { get; set; }
        public bool Paid { get; set; }
        public Nullable<int> PayCrID { get; set; }
        public bool InternalAdjustment { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Allocated { get; set; }
    
        public virtual CreditReason CreditReason { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual PalletMovement PalletMovement { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalletMovement> PalletMovement1 { get; set; }
    }
}
