//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Address = new HashSet<Address>();
            this.Credit = new HashSet<Credit>();
            this.Invoice = new HashSet<Invoice>();
            this.Order = new HashSet<Order>();
            this.PalletMovement = new HashSet<PalletMovement>();
            this.PartielCredit = new HashSet<PartielCredit>();
            this.Payment = new HashSet<Payment>();
            this.PriceList = new HashSet<PriceList>();
            this.StockComments = new HashSet<StockComments>();
            this.StockMovements = new HashSet<StockMovements>();
            this.TempStatements = new HashSet<TempStatements>();
        }
    
        public int CustomerID { get; set; }
        public string CustomerRef { get; set; }
        public string CustomerTypeID { get; set; }
        public bool StandardPriceList { get; set; }
        public string DealTypeID { get; set; }
        public bool Collection { get; set; }
        public string PaymentMethodID { get; set; }
        public string CustomerNotes { get; set; }
        public string CustomerComments { get; set; }
        public string CustomerName { get; set; }
        public string CustomerVATNumber { get; set; }
        public string ContactName { get; set; }
        public string ContactTelephone { get; set; }
        public string ContactEmail { get; set; }
        public bool OnHold { get; set; }
        public Nullable<System.DateTime> DateonHold { get; set; }
        public string OnHoldReason { get; set; }
        public Nullable<decimal> TermsDiscountPercentage { get; set; }
        public bool Active { get; set; }
        public string CustomerGroupID { get; set; }
        public string CollectionPoint { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credit> Credit { get; set; }
        public virtual SupplierDepot SupplierDepot { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Customer Customer2 { get; set; }
        public virtual Customer Customer11 { get; set; }
        public virtual Customer Customer3 { get; set; }
        public virtual CustomerGroup CustomerGroup { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual DealType DealType { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalletMovement> PalletMovement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartielCredit> PartielCredit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceList> PriceList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockComments> StockComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMovements> StockMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempStatements> TempStatements { get; set; }
    }
}
