//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Credit = new HashSet<Credit>();
            this.InvoiceDetail = new HashSet<InvoiceDetail>();
            this.PaymentAllocation = new HashSet<PaymentAllocation>();
        }
    
        public int InvoiceID { get; set; }
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public int AddressID { get; set; }
        public string VATTypeID { get; set; }
        public string CurrencyID { get; set; }
        public string InvoiceTypeID { get; set; }
        public string InvoiceStatusID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Transport { get; set; }
        public decimal VAT { get; set; }
        public decimal VATRate { get; set; }
        public decimal InvoiceTotal { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<System.DateTime> EarlyDiscountPaymentDate { get; set; }
        public Nullable<decimal> DiscountApplied { get; set; }
        public string DiscountType { get; set; }
        public string InvoiceLineNotes { get; set; }
        public string InvoiceNotes { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public bool Paid { get; set; }
        public int NumberofPallets { get; set; }
        public decimal PalletDeposit { get; set; }
        public bool Sent { get; set; }
        public bool InternalCorrection { get; set; }
        public Nullable<bool> Invoiced { get; set; }
        public Nullable<bool> Printed { get; set; }
        public Nullable<bool> Emailed { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<decimal> SubTotalWithoutVAT { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credit> Credit { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual InvoiceStatus InvoiceStatus { get; set; }
        public virtual InvoiceType InvoiceType { get; set; }
        public virtual Order Order { get; set; }
        public virtual VATType VATType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentAllocation> PaymentAllocation { get; set; }
        public virtual Invoice Invoice1 { get; set; }
        public virtual Invoice Invoice2 { get; set; }
    }
}
