//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceDetail()
        {
            this.ShipmentItem = new HashSet<ShipmentItem>();
            this.StockComments = new HashSet<StockComments>();
        }
    
        public int InvoiceLineID { get; set; }
        public int InvoiceID { get; set; }
        public string ProductID { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> PricingUnit { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Cost { get; set; }
        public int LineType { get; set; }
        public string LineDescription { get; set; }
        public Nullable<int> DetailType { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> Pallets { get; set; }
        public Nullable<int> ItemPerPallet { get; set; }
        public Nullable<int> OrderDetailID { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual InvoiceDetail InvoiceDetail1 { get; set; }
        public virtual InvoiceDetail InvoiceDetail2 { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentItem> ShipmentItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockComments> StockComments { get; set; }
    }
}
