//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Merlin_Data3Entities : DbContext
    {
        public Merlin_Data3Entities()
            : base("name=Merlin_Data3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessGroup> AccessGroup { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<AddressType> AddressType { get; set; }
        public virtual DbSet<CancellationReason> CancellationReason { get; set; }
        public virtual DbSet<Colour> Colour { get; set; }
        public virtual DbSet<Credit> Credit { get; set; }
        public virtual DbSet<CreditReason> CreditReason { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerGroup> CustomerGroup { get; set; }
        public virtual DbSet<CustomerType> CustomerType { get; set; }
        public virtual DbSet<DealNumber> DealNumber { get; set; }
        public virtual DbSet<DealType> DealType { get; set; }
        public virtual DbSet<DispatchMethod> DispatchMethod { get; set; }
        public virtual DbSet<Feature> Feature { get; set; }
        public virtual DbSet<Haulier> Haulier { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetail { get; set; }
        public virtual DbSet<InvoiceStatus> InvoiceStatus { get; set; }
        public virtual DbSet<InvoiceType> InvoiceType { get; set; }
        public virtual DbSet<NeckFinish> NeckFinish { get; set; }
        public virtual DbSet<OldPasswords> OldPasswords { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<PalletMovement> PalletMovement { get; set; }
        public virtual DbSet<PalletMovementType> PalletMovementType { get; set; }
        public virtual DbSet<PartielCredit> PartielCredit { get; set; }
        public virtual DbSet<PasswordPolicy> PasswordPolicy { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<PaymentAllocation> PaymentAllocation { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethod { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<PriceList> PriceList { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductGroup> ProductGroup { get; set; }
        public virtual DbSet<Shipment> Shipment { get; set; }
        public virtual DbSet<ShipmentItem> ShipmentItem { get; set; }
        public virtual DbSet<ShipmentStatus> ShipmentStatus { get; set; }
        public virtual DbSet<Size> Size { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockComments> StockComments { get; set; }
        public virtual DbSet<StockMovements> StockMovements { get; set; }
        public virtual DbSet<StockMovementType> StockMovementType { get; set; }
        public virtual DbSet<StockType> StockType { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SupplierDepot> SupplierDepot { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TempStatements> TempStatements { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<VATRate> VATRate { get; set; }
        public virtual DbSet<VATType> VATType { get; set; }
        public virtual DbSet<weight> weight { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Company> Company { get; set; }
    }
}
