//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetail()
        {
            this.InvoiceDetail = new HashSet<InvoiceDetail>();
        }
    
        public int OrderLineID { get; set; }
        public string ProductID { get; set; }
        public int Quantity { get; set; }
        public decimal PricingUnit { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal StandardPrice { get; set; }
        public decimal LineDiscount { get; set; }
        public decimal LineTotal { get; set; }
        public string LineDescription { get; set; }
        public int DetailType { get; set; }
        public bool Deleted { get; set; }
        public int UserID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> DealNumber { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> PerPallet { get; set; }
        public Nullable<int> PalletCount { get; set; }
        public Nullable<int> PriceID { get; set; }
        public Nullable<int> OriginalQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetail { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
