//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalletMovement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PalletMovement()
        {
            this.Credit = new HashSet<Credit>();
        }
    
        public int PalletMovementID { get; set; }
        public int PalletMovementTypeID { get; set; }
        public System.DateTime MovementDate { get; set; }
        public int CustomerID { get; set; }
        public string ProductID { get; set; }
        public Nullable<int> ShipmentID { get; set; }
        public Nullable<int> CreditID { get; set; }
        public int PalletQuantity { get; set; }
        public decimal PalletPrice { get; set; }
        public string SupplierID { get; set; }
        public string DeliveryNote { get; set; }
        public Nullable<int> Refunded { get; set; }
        public Nullable<bool> Delivered { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ReturnedToSupplier { get; set; }
        public string SupplierReturnRef { get; set; }
        public string CustomerSupplier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credit> Credit { get; set; }
        public virtual Credit Credit1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual PalletMovementType PalletMovementType { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Shipment Shipment { get; set; }
        public virtual Supplier Supplier1 { get; set; }
    }
}
