//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.Security.Cryptography;

    public partial class PasswordPolicy : User
    {
        public int PasswordPolicyID { get; set; }
        public int MinumumLength { get; set; }
        public bool MixedCase { get; set; }
        public bool MustUseNumbers { get; set; }
        public bool MustUseSpecialCharacters { get; set; }
        public bool ForceChangeAfterReset { get; set; }
        public int ExpireAfter { get; set; }
        public int GiveWarning { get; set; }
        public int ReuseAfterXChanges { get; set; }
        public int ReuseAfterXDays { get; set; }

    }
    
}
