//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentAllocation
    {
        public int AllocationID { get; set; }
        public int InvoiceID { get; set; }
        public decimal PaymentAmount { get; set; }
        public bool Reversed { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
