//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int CustomerID { get; set; }
        public string CurrencyID { get; set; }
        public string PaymentMethodID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal PaymentAmount { get; set; }
        public string PaymentReference { get; set; }
        public string PaymentDirection { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> InternalAdjustment { get; set; }
        public Nullable<bool> Reversed { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
