//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PermissionID { get; set; }
        public string ScreenName { get; set; }
        public bool Office { get; set; }
        public bool Finance { get; set; }
        public bool Warehouse { get; set; }
        public bool Admin { get; set; }
    }
}
