//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceList
    {
        public int PriceID { get; set; }
        public int CustomerID { get; set; }
        public string ProductID { get; set; }
        public string SupplierDepotID { get; set; }
        public decimal Price { get; set; }
        public System.DateTime EffectiveFromDate { get; set; }
        public System.DateTime DateChanged { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Editedby { get; set; }
        public bool Standard { get; set; }
        public bool Agreed { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
        public virtual SupplierDepot SupplierDepot { get; set; }
    }
}
