//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.InvoiceDetail = new HashSet<InvoiceDetail>();
            this.OrderDetail = new HashSet<OrderDetail>();
            this.PalletMovement = new HashSet<PalletMovement>();
            this.PartielCredit = new HashSet<PartielCredit>();
            this.PriceList = new HashSet<PriceList>();
            this.Stock = new HashSet<Stock>();
            this.StockComments = new HashSet<StockComments>();
            this.StockMovements = new HashSet<StockMovements>();
        }
    
        public string ProductID { get; set; }
        public string SupplierCode { get; set; }
        public string ProductGroupID { get; set; }
        public string SupplierID { get; set; }
        public string SizeID { get; set; }
        public string NeckFinishID { get; set; }
        public string FeatureID { get; set; }
        public string AECID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<decimal> PriceUnit { get; set; }
        public Nullable<int> PerPallet { get; set; }
        public string PalletID { get; set; }
        public bool Inactive { get; set; }
        public string InactiveNotes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string WeightID { get; set; }
        public string ColourID { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
    
        public virtual Colour Colour { get; set; }
        public virtual Feature Feature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetail { get; set; }
        public virtual NeckFinish NeckFinish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalletMovement> PalletMovement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartielCredit> PartielCredit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceList> PriceList { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual Size Size { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual weight weight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockComments> StockComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMovements> StockMovements { get; set; }
    }
}
