//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipment()
        {
            this.PalletMovement = new HashSet<PalletMovement>();
        }
    
        public int ShipmentID { get; set; }
        public int OrderID { get; set; }
        public string ShipmentStatusID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public System.DateTime DatePicked { get; set; }
        public System.DateTime DateDispatched { get; set; }
        public System.DateTime DateDelivered { get; set; }
        public System.DateTime DateCancelled { get; set; }
        public Nullable<bool> Printed { get; set; }
    
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalletMovement> PalletMovement { get; set; }
        public virtual ShipmentStatus ShipmentStatus { get; set; }
    }
}
