//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockComments
    {
        public int StockCommentID { get; set; }
        public Nullable<int> InvoiceItemID { get; set; }
        public string ProductID { get; set; }
        public System.DateTime CommentDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public int Pallets { get; set; }
        public int Qty { get; set; }
        public string Comment { get; set; }
        public bool Removed { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual InvoiceDetail InvoiceDetail { get; set; }
        public virtual Product Product { get; set; }
    }
}
