//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int StockID { get; set; }
        public string ProductID { get; set; }
        public int OnHand { get; set; }
        public Nullable<bool> Locked { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockedOn { get; set; }
        public Nullable<int> Pallets { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
