//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin_web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempStatements
    {
        public int StatementID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<bool> sent { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<bool> printed { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
